### ISSUE TITLE
pwm cannot be resolved to a type

### ISSUE THREAD

**Issue by indy0130** [saileshmittal/phonegap-system-notification-plugin#1]
After tried to install your plugin in PhoneGap 0.9.2 I get this error message.

Do you have an idea?

**Comment by saileshmittal** [comment]
"pwm" was my personal class. sorry for the inconvenience.
I changed it to "myActivityClass.class" but you must rename to the activity that needs to get launched. This should be the one that extends DroidGap class.

**Comment by saileshmittal** [comment]
thanks for pointing it out.

**Comment by KrishnaShetty** [comment]
For phonegap-1.3.0, I got resolve error onPause and onResume. Below change required
   @Override
    public void onPause(boolean multitasking)

   @Override
    public void onResume(boolean multitasking)
